<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <AssemblyVersion>25.10.5.201</AssemblyVersion>
    <FileVersion>25.10.5.201</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Templates\Templates.csproj" />
    <ProjectReference Include="..\..\Infrastructures\Infrastructures.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Widgets\" />
  </ItemGroup>

</Project>
