<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>25.10.5.42</AssemblyVersion>
    <FileVersion>25.10.5.42</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QueryService\QueryService.csproj" />
  </ItemGroup>

</Project>
